name: flutter_app_demo
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: "^0.4.2"
  common_utils: ^1.1.1
  flustars: ^0.2.5
  dio: ^2.1.5
  fluttertoast: ^3.0.4
  rxdart: ^0.21.0
  event_bus: ^1.1.0
  qr_flutter: ^1.1.3
  image_picker: ^0.6.0+9
  cached_network_image: ^0.8.0
  page_indicator: ^0.2.0
  sqflite: ^1.1.0
  audioplayer: ^0.5.2
  webview_flutter: ^0.3.9+1
  url_launcher: ^5.0.3
  sprintf: ^4.0.2
  flutter_drag_scale:
    git: https://github.com/LiuC520/flutter_drag_scale.git
  flutter_custom_bottom_tab_bar:
    git: https://github.com/LiuC520/flutter_custom_bottom_tab_bar.git

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  # assets-generator-begin
  # images/*
    - images/transfer_ico.png
    - images/photo_ico.png
    - images/material_ico.png
    - images/voice_left.png
    - images/file_ico.png
    - images/img.jpg
    - images/camera_ico.png
    - images/chat_room_left_voice.png
    - images/search.png
    - images/left_voice_3.png
    - images/pwd.png
    - images/left_voice_2.png
    - images/voice_volume_1.png
    - images/voice_volume_3.png
    - images/left_voice_1.png
    - images/group_delete_ico.png
    - images/voice_volume_2.png
    - images/voice_volume_6.png
    - images/cancel_voice.png
    - images/voice_too_short_ico.png
    - images/voice_volume_7.png
    - images/voice_volume_5.png
    - images/voice_volume_4.png
    - images/delete.png
    - images/group_add_ico.png
    - images/WechatIMG1.jpeg
  # images/emoji/*
    - images/emoji/fuck27.png
    - images/emoji/fuck33.png
    - images/emoji/fuck32.png
    - images/emoji/fuck26.png
    - images/emoji/fuck30.png
    - images/emoji/fuck24.png
    - images/emoji/fuck18.png
    - images/emoji/fuck19.png
    - images/emoji/fuck31.png
    - images/emoji/fuck09.png
    - images/emoji/fuck35.png
    - images/emoji/fuck21.png
    - images/emoji/fuck20.png
    - images/emoji/fuck34.png
    - images/emoji/fuck08.png
    - images/emoji/fuck22.png
    - images/emoji/fuck37.png
    - images/emoji/fuck23.png
    - images/emoji/fuck93.png
    - images/emoji/fuck50.png
    - images/emoji/fuck79.png
    - images/emoji/fuck51.png
    - images/emoji/fuck45.png
    - images/emoji/fuck86.png
    - images/emoji/fuck90.png
    - images/emoji/fuck84.png
    - images/emoji/fuck53.png
    - images/emoji/fuck47.png
    - images/emoji/fuck46.png
    - images/emoji/fuck52.png
    - images/emoji/fuck85.png
    - images/emoji/fuck95.png
    - images/emoji/fuck81.png
    - images/emoji/fuck56.png
    - images/emoji/fuck42.png
    - images/emoji/fuck43.png
    - images/emoji/fuck57.png
    - images/emoji/fuck80.png
    - images/emoji/fuck94.png
    - images/emoji/fuck100.png
    - images/emoji/fuck82.png
    - images/emoji/fuck96.png
    - images/emoji/fuck69.png
    - images/emoji/fuck41.png
    - images/emoji/fuck55.png
    - images/emoji/fuck40.png
    - images/emoji/fuck68.png
    - images/emoji/fuck97.png
    - images/emoji/fuck83.png
    - images/emoji/fuck65.png
    - images/emoji/fuck71.png
    - images/emoji/fuck58.png
    - images/emoji/fuck64.png
    - images/emoji/fuck99.png
    - images/emoji/fuck66.png
    - images/emoji/fuck67.png
    - images/emoji/fuck98.png
    - images/emoji/fuck77.png
    - images/emoji/fuck63.png
    - images/emoji/fuck76.png
    - images/emoji/fuck48.png
    - images/emoji/defaultEmoji.png
    - images/emoji/fuck75.png
    - images/emoji/fuck61.png
    - images/emoji/fuck49.png
    - images/emoji/fuck06.png
    - images/emoji/fuck12.png
    - images/emoji/collection.png
    - images/emoji/fuck13.png
    - images/emoji/fuck07.png
    - images/emoji/fuck11.png
    - images/emoji/fuck05.png
    - images/emoji/fuck39.png
    - images/emoji/fuck38.png
    - images/emoji/fuck04.png
    - images/emoji/fuck10.png
    - images/emoji/fuck28.png
    - images/emoji/fuck14.png
    - images/emoji/fuck01.png
    - images/emoji/fuck15.png
    - images/emoji/fuck29.png
    - images/emoji/fuck03.png
    - images/emoji/fuck16.png
    - images/emoji/fuck02.png
  # assets-generator-end
#
#    - images/img.jpg
#    - images/voice_left.png
#    - images/pwd.png
#    - images/chat_room_left_voice.png
#    - images/delete.png
#
#    - images/file_ico.png
#    - images/photo_ico.png
#    - images/transfer_ico.png
#    - images/material_ico.png
#    - images/camera_ico.png
#
#    - images/left_voice_1.png
#    - images/left_voice_2.png
#    - images/left_voice_3.png
#    - images/left_voice_3.png
#
#    - images/voice_volume_7.png
#    - images/voice_volume_6.png
#    - images/voice_volume_5.png
#    - images/voice_volume_4.png
#    - images/voice_volume_3.png
#    - images/voice_volume_2.png
#    - images/voice_volume_1.png
#    - images/cancel_voice.png
#    - images/voice_too_short_ico.png
#
#
#    #      表情图片资源
#    - images/emoji/fuck27.png
#    - images/emoji/fuck33.png
#    - images/emoji/fuck32.png
#    - images/emoji/fuck26.png
#    - images/emoji/fuck30.png
#    - images/emoji/fuck24.png
#    - images/emoji/fuck18.png
#    - images/emoji/fuck19.png
#    - images/emoji/fuck31.png
#    - images/emoji/fuck09.png
#    - images/emoji/fuck35.png
#    - images/emoji/fuck21.png
#    - images/emoji/fuck20.png
#    - images/emoji/fuck34.png
#    - images/emoji/fuck08.png
#    - images/emoji/fuck22.png
#    - images/emoji/fuck37.png
#    - images/emoji/fuck23.png
#    - images/emoji/fuck93.png
#    - images/emoji/fuck50.png
#    - images/emoji/fuck79.png
#    - images/emoji/fuck51.png
#    - images/emoji/fuck45.png
#    - images/emoji/fuck86.png
#    - images/emoji/fuck90.png
#    - images/emoji/fuck84.png
#    - images/emoji/fuck53.png
#    - images/emoji/fuck47.png
#    - images/emoji/fuck46.png
#    - images/emoji/fuck52.png
#    - images/emoji/fuck85.png
#    - images/emoji/fuck95.png
#    - images/emoji/fuck81.png
#    - images/emoji/fuck56.png
#    - images/emoji/fuck42.png
#    - images/emoji/fuck43.png
#    - images/emoji/fuck57.png
#    - images/emoji/fuck80.png
#    - images/emoji/fuck94.png
#    - images/emoji/fuck100.png
#    - images/emoji/fuck82.png
#    - images/emoji/fuck96.png
#    - images/emoji/fuck69.png
#    - images/emoji/fuck41.png
#    - images/emoji/fuck55.png
#    - images/emoji/fuck40.png
#    - images/emoji/fuck68.png
#    - images/emoji/fuck97.png
#    - images/emoji/fuck83.png
#    - images/emoji/fuck65.png
#    - images/emoji/fuck71.png
#    - images/emoji/fuck58.png
#    - images/emoji/fuck64.png
#    - images/emoji/fuck99.png
#    - images/emoji/fuck66.png
#    - images/emoji/fuck67.png
#    - images/emoji/fuck98.png
#    - images/emoji/fuck77.png
#    - images/emoji/fuck63.png
#    - images/emoji/fuck76.png
#    - images/emoji/fuck48.png
#    - images/emoji/defaultEmoji.png
#    - images/emoji/fuck75.png
#    - images/emoji/fuck61.png
#    - images/emoji/fuck49.png
#    - images/emoji/fuck06.png
#    - images/emoji/fuck12.png
#    - images/emoji/collection.png
#    - images/emoji/fuck13.png
#    - images/emoji/fuck07.png
#    - images/emoji/fuck11.png
#    - images/emoji/fuck05.png
#    - images/emoji/fuck39.png
#    - images/emoji/fuck38.png
#    - images/emoji/fuck04.png
#    - images/emoji/fuck10.png
#    - images/emoji/fuck28.png
#    - images/emoji/fuck14.png
#    - images/emoji/fuck01.png
#    - images/emoji/fuck15.png
#    - images/emoji/fuck29.png
#    - images/emoji/fuck03.png
#    - images/emoji/fuck16.png
#    - images/emoji/fuck02.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
